### ISSUE TITLE
Switch to GPL license according to dict.cc's terms of use

### ISSUE THREAD

**Issue by kolletzki** [derhuerst/dict-cc-cli#7]
The [dict.cc page to download a dump](http://www1.dict.cc/translation_file_request.php?l=e) states that 

> Programs using data of dict.cc must be subject to the terms of the GPL.

Please change the license of this repo to GPL to be compliant to dict.cc's terms of use.

**Comment by GuyXY** [comment]
You may want to replace the license.md file as well.
